# Generated by Django 2.2.2 on 2019-06-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video_posted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='posted_at',
            new_name='uploaded_at',
        ),
    ]
