# Generated by Django 2.2.2 on 2019-06-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190620_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='thumbs_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='thumbs_up',
            field=models.IntegerField(default=0),
        ),
    ]
