# Generated by Django 2.2.2 on 2019-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190621_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
